# Conexiones locales
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Conexiones desde la red de Docker
host    all             all             172.20.0.0/16           md5

# Replicación
host    replication     replicator      172.20.0.0/16           md5