# Configuración básica
listen_addresses = '*'
port = 5432

# Replicación
wal_level = replica
max_wal_senders = 3
max_replication_slots = 3
wal_keep_size = 64
hot_standby = on

# Logging
log_destination = 'stderr'
logging_collector = off