name: StoreSystem_Variables

on:
  workflow_call:

env:
  App_name: 'StoreSystem'
  Dotnet_Version: '10'
  Node_Version: '22'
  Postgres_Version: '16'
  SqlServer_Version: '2022'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TipoEjecucion: 'Validacion de variables'

    steps:
      - name: Ejecutar checkout
        uses: actions/checkout@v4

      - name: Mostrar variables globales
        env:
          mensaje: Iniciando validación de variables del proyecto StoreSystem
        run: |
          echo "Aplicacion: $App_name"
          echo "Version de .NET: $Dotnet_Version"
          echo "Version de Node: $Node_Version"
          echo "Version de PostgreSQL: $Postgres_Version"
          echo "Version de SQL Server: $SqlServer_Version"
          echo "Tipo de ejecucion: $TipoEjecucion"
          echo $mensaje

      - name: Crear Variable
        run: echo "framework=NET10" >> $GITHUB_ENV

      - name: Usar Variable creada
        run: |
          echo "Framework creado: $framework"
          echo "Rama de liberacion: ${{ github.ref }}"

      - name: Variables del repositorio
        run: |
          echo "${{ vars.PROYECT_DESCRIPTION }}"
          echo "$GITHUB_WORKSPACE"

      - name: Leer y modificar appsettings.json
        shell: pwsh
        run: |
          $path = "$env:GITHUB_WORKSPACE/AuthAPI/appsettings.json"
          $json = Get-Content $path -Raw | ConvertFrom-Json

          echo "Antes del cambio:"
          echo ($json | ConvertTo-Json -Depth 10)

          $json.ConnectionStrings.WriteConnection = "Server=sql-server,1433;Database=AuthDB;User Id=sa;Password=WORKFLOW_TEST;TrustServerCertificate=True;"
          $json.ConnectionStrings.ReadConnection = "Server=sql-server,1433;Database=AuthDB;User Id=sa;Password=WORKFLOW_TEST;TrustServerCertificate=True;"

          $json | ConvertTo-Json -Depth 10 | Set-Content $path

          echo "Despues del cambio:"
          echo ($json | ConvertTo-Json -Depth 10)