name: StoreSystem_Docker_AuthAPI

on:
  push:
    branches:
      - features/docker-workflow

jobs:
  build:
    uses: ./.github/workflows/docker-reusable.yml
    with:
      image_name: auth-api
      context: .
      dockerfile: ./AuthAPI/Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}