name: StoreSystem_Docker_Frontend

on:
  push:
    branches:
      - features/docker-workflow

jobs:
  build:
    uses: ./.github/workflows/docker-reusable.yml
    with:
      image_name: store-frontend
      context: ./store-frontend
      dockerfile: ./store-frontend/Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}