name: StoreSystem_Docker_AuthAPI_V2
on:
  push:
    branches:
      - features/docker-workflow-v2
jobs:
  build:
    uses: ./.github/workflows/docker-reusable-v2.yml
    with:
      image_name: auth-api
      context: .
      dockerfile: ./AuthAPI/Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}