name: StoreSystem_Docker_StoreAPI_GCP_V2
on:
  push:
    branches:
      - features/google-cloud-v2
jobs:
  build:
    uses: ./.github/workflows/docker-reusable-gcp-v2.yml
    with:
      image_name: store-api
      context: ./store-api
      dockerfile: ./store-api/Dockerfile
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}