name: StoreSystem_Docker_Frontend_GCP

on:
  push:
    branches:
      - features/google-cloud

jobs:
  build:
    uses: ./.github/workflows/docker-reusable-gcp.yml
    with:
      image_name: store-frontend
      context: ./store-frontend
      dockerfile: ./store-frontend/Dockerfile
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}