- name: Ejecutar pruebas e2e StoreAPI
        run: npm run test:e2e
        working-directory: ./store-api
        env:
          DATABASE_URL: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          DATABASE_URL_WRITE: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          DATABASE_URL_READ: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          JWT_SECRET: "EstoEsUnaClaveSecretaMuyLargaParaJWT2024!#$%"
          AUTH_API_URL: "http://localhost:5163"
          PORT: "3000"
          NODE_ENV: "test"