name: StoreSystem_Pruebas

on:
  push:
    branches:
      - features/workflow-pruebas
  pull_request:
    branches:
      - master

jobs:
  test-store-api:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: storedb_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Revision de código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias StoreAPI
        run: npm ci
        working-directory: ./store-api

       - name: Esperar a PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Esperando a PostgreSQL..."
            sleep 2
          done

      - name: Ejecutar migraciones
        run: npx prisma migrate deploy
        working-directory: ./store-api
        env:
          DATABASE_URL: "postgresql://postgres:testpassword@localhost:5432/storedb_test"

      - name: Ejecutar pruebas e2e StoreAPI
        run: npm run test:e2e
        working-directory: ./store-api
        env:
          DATABASE_URL: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          DATABASE_URL_WRITE: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          DATABASE_URL_READ: "postgresql://postgres:testpassword@localhost:5432/storedb_test"
          JWT_SECRET: "EstoEsUnaClaveSecretaMuyLargaParaJWT2024!#$%"
          AUTH_API_URL: "http://localhost:5163"
          PORT: "3000"
          NODE_ENV: "test"